site_name: phospho docs
site_url: https://phospho-app.github.io/docs/

theme:
  name: material
  icon:
    logo: fontawesome/solid/vial
  features:
    - content.tabs.link
    - navigation.tabs
  palette:
    # Palette toggle for dark mode
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for light mode
    - scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption

nav:
  - Platform: 
    - index.md
    - getting-started.md
    - Import data: 
      - import-data/import-file.md
      - import-data/api-integration.md
      - import-data/import-langsmith.md
      - import-data/import-langfuse.md
      - import-data/tracing.md
    - self-hosting.md
    - cli.md
  - Guides:
    - guides/welcome-guide.md
  - API Reference:
    - api-reference/introduction.md
  - Examples:
    - examples/introduction.md