[project]
name = "mkdocs_phospho"
version = "0.1.0"
description = "phospho docs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material>=9.5.49",
    "mkdocs>=1.6.1",
    "mkdocs-glightbox>=0.4.0",
]
